-- tbl_content_kanji에 한자 추가
-- 부수 및 특수 한자 추가용

INSERT INTO tbl_content_kanji
  (character, meaning_ko, meaning_ko_detail, components, stroke_count,
   on_reading, kun_reading, meaning_ja, jlpt_level, created_at)
VALUES
  ('鬯', '향풀 창, 울창주 창', '향풀 창, 울창주 창', '凵(입벌릴 감) + 米(쌀 미) + 匕(비수 비)', 10, '', '', '', NULL, now()),
  ('彡', '터럭 삼', '터럭 삼', '', 3, '', '', '', NULL, now()),
  ('冖', '덮을 멱', '덮을 멱', '', 2, '', '', '', NULL, now()),
  ('丿', '삐침 별', '삐침 별', '', 1, '', '', '', NULL, now()),
  ('吾', '나 오', '나 오', '五(다섯 오) + 口(입 구)', 7, '', '', '', NULL, now()),
  ('亖', '넉 사', '넉 사', '', 4, '', '', '', NULL, now()),
  ('丶', '점 주', '점 주', '', 1, '', '', '', NULL, now()),
  ('亅', '갈고리 궐', '갈고리 궐', '', 1, '', '', '', NULL, now()),
  ('宀', '갓 머리', '갓 머리, 집 면', '', 3, '', '', '', NULL, now()),
  ('亠', '돼지해머리 두', '돼지해머리 두', '', 2, '', '', '', NULL, now()),
  ('丨', '뚫을 곤', '뚫을 곤', '', 1, '', '', '', NULL, now()),
  ('𠂇', '왼손 좌', '왼손 좌', '', 2, '', '', '', NULL, now()),
  ('䒑', '초두머리 초', '초두머리 초', '', 3, '', '', '', NULL, now()),
  ('艹', '초두머리 초', '초두머리 초', '', 3, '', '', '', NULL, now()),
  ('圥', '버섯 록', '버섯 록', '', 5, '', '', '', NULL, now()),
  ('尸', '주검 시', '주검 시', '', 3, '', '', '', NULL, now()),
  ('屮', '왼손 좌, 싹날 철', '왼손 좌, 싹날 철', '', 3, '', '', '', NULL, now()),
  ('冂', '멀 경', '멀 경', '', 2, '', '', '', NULL, now()),
  ('巛', '개천 천', '개천 천, 순할 순', '', 3, '', '', '', NULL, now()),
  ('冫', '얼음 빙', '이수변, 얼음 빙', '', 2, '', '', '', NULL, now()),
  ('气', '기운 기', '기운 기', '', 4, '', '', '', NULL, now()),
  ('凵', '입벌릴 감', '입벌릴 감', '', 2, '', '', '', NULL, now()),
  ('广', '집 엄', '집 엄', '', 3, '', '', '', NULL, now()),
  ('勹', '쌀 포', '쌀 포', '', 2, '', '', '', NULL, now()),
  ('廴', '길게걸을 인', '길게걸을 인', '', 3, '', '', '', NULL, now()),
  ('匕', '비수 비', '비수 비', '', 2, '', '', '', NULL, now()),
  ('廾', '받들 공', '받들 공', '', 3, '', '', '', NULL, now()),
  ('匚', '상자 방', '상자 방', '', 2, '', '', '', NULL, now()),
  ('弋', '주살 익', '주살 익', '', 3, '', '', '', NULL, now()),
  ('卜', '점 복', '점 복', '', 2, '', '', '', NULL, now()),
  ('彳', '조금걸을 척', '조금걸을 척', '', 3, '', '', '', NULL, now()),
  ('厂', '기슭 엄', '기슭 엄', '', 2, '', '', '', NULL, now()),
  ('釆', '분별할 변', '분별할 변', '丿(삐침 별) + 米(쌀 미)', 7, '', '', '', NULL, now()),
  ('龍', '용 룡', '용 룡', '立(설 립) + 月(달 월) + 三(석 삼) + 彡(터럭 삼)', 16, '', '', '', NULL, now()),
  ('髟', '터럭발 표', '터럭발 표', '長(길 장) + 彡(터럭 삼)', 10, '', '', '', NULL, now()),
  ('韋', '가죽 위', '가죽 위', '口(입 구) + 舛(어그러질 천)', 9, '', '', '', NULL, now()),
  ('鬲', '솥 력', '솥 력', '冂(멀 경) + 儿(어진사람 인) + 丫(가닥 아)', 10, '', '', '', NULL, now()),
  ('禾', '벼 화', '벼 화', '丿(삐침 별) + 木(나무 목)', 5, '', '', '', NULL, now()),
  ('隶', '미칠 이', '미칠 이', '又(또 우) + 八(여덟 팔) 형태', 8, '', '', '', NULL, now()),
  ('殳', '창 수', '창 수', '几(안석 궤) + 又(또 우)', 4, '', '', '', NULL, now()),
  ('儿', '어진사람 인', '어진사람 인', '', 2, '', '', '', NULL, now()),
  ('几', '안석 궤', '안석 궤', '', 2, '', '', '', NULL, now()),
  ('厶', '사사 사', '사사 사', '', 2, '', '', '', NULL, now()),
  ('囗', '큰입 구', '큰입 구', '', 3, '', '', '', NULL, now()),
  ('幺', '작을 요', '작을 요', '', 3, '', '', '', NULL, now()),
  ('彐', '돼지머리 계', '돼지머리 계', '', 3, '', '', '', NULL, now()),
  ('戈', '창 과', '창 과', '', 4, '', '', '', NULL, now()),
  ('戶', '지게 호', '지게 호', '', 4, '', '', '', NULL, now()),
  ('歹', '죽을사변 알', '죽을사변 알', '', 4, '', '', '', NULL, now()),
  ('毋', '말 무', '말 무', '', 4, '', '', '', NULL, now()),
  ('瓜', '오이 과', '오이 과', '', 5, '', '', '', NULL, now()),
  ('疋', '짝 필', '짝 필', '', 5, '', '', '', NULL, now()),
  ('疒', '병들녁 녁', '병들녁 녁', '', 5, '', '', '', NULL, now()),
  ('癶', '필발 발', '필발 발', '', 5, '', '', '', NULL, now()),
  ('耂', '늙을 로', '늙을 로', '', 4, '', '', '', NULL, now()),
  ('而', '말이을 이', '말이을 이', '', 6, '', '', '', NULL, now()),
  ('耒', '쟁기 뢰', '쟁기 뢰', '', 6, '', '', '', NULL, now()),
  ('聿', '붓 율', '붓 율', '', 6, '', '', '', NULL, now()),
  ('舛', '어그러질 천', '어그러질 천', '', 6, '', '', '', NULL, now()),
  ('艮', '괘이름 간', '괘이름 간', '', 6, '', '', '', NULL, now()),
  ('虍', '범 호', '범 호', '', 6, '', '', '', NULL, now()),
  ('豕', '돼지 시', '돼지 시', '', 7, '', '', '', NULL, now()),
  ('豸', '갖은돼지시변 치', '갖은돼지시변 치', '', 7, '', '', '', NULL, now()),
  ('辰', '별 진', '별 진', '', 7, '', '', '', NULL, now()),
  ('酉', '닭 유, 술 유', '닭 유, 술 유', '', 7, '', '', '', NULL, now()),
  ('辶', '쉬엄쉬엄 갈 착(부수 형태)', '쉬엄쉬엄 갈 착(부수 형태)', '', 3, '', '', '', NULL, now()),
  ('氵', '삼수변', '삼수변', '', 3, '', '', '', NULL, now()),
  ('辵', '쉬엄쉬엄 갈 착', '쉬엄쉬엄 갈 착', '', 7, '', '', '', NULL, now()),
  ('𠂉', '[미상 한자]', '[미상 한자]', '', 2, '', '', '', NULL, now())
ON CONFLICT (character) DO NOTHING;

-- 특정 한자 데이터 수정
UPDATE tbl_content_kanji SET components = '大(클 대) + 一(하나 일)' WHERE character = '立';
UPDATE tbl_content_kanji SET components = '⺍(작을 소) + 田(밭 전) + 十(열 십)' WHERE character = '単';
UPDATE tbl_content_kanji SET components = '五(다섯 오)' WHERE character = '五';
UPDATE tbl_content_kanji SET components = '幺(작을 요) + 白(흰 백) + 木(나무 목)' WHERE character = '楽';



INSERT INTO tbl_content_kana (character, romaji, script, kind, created_at) VALUES
  ('あ', 'a', 'hira', 'seion', NOW()),
  ('ア', 'a', 'kata', 'seion', NOW()),
  ('い', 'i', 'hira', 'seion', NOW()),
  ('イ', 'i', 'kata', 'seion', NOW()),
  ('う', 'u', 'hira', 'seion', NOW()),
  ('ウ', 'u', 'kata', 'seion', NOW()),
  ('え', 'e', 'hira', 'seion', NOW()),
  ('エ', 'e', 'kata', 'seion', NOW()),
  ('お', 'o', 'hira', 'seion', NOW()),
  ('オ', 'o', 'kata', 'seion', NOW()),
  ('か', 'ka', 'hira', 'seion', NOW()),
  ('カ', 'ka', 'kata', 'seion', NOW()),
  ('き', 'ki', 'hira', 'seion', NOW()),
  ('キ', 'ki', 'kata', 'seion', NOW()),
  ('く', 'ku', 'hira', 'seion', NOW()),
  ('ク', 'ku', 'kata', 'seion', NOW()),
  ('け', 'ke', 'hira', 'seion', NOW()),
  ('ケ', 'ke', 'kata', 'seion', NOW()),
  ('こ', 'ko', 'hira', 'seion', NOW()),
  ('コ', 'ko', 'kata', 'seion', NOW()),
  ('さ', 'sa', 'hira', 'seion', NOW()),
  ('サ', 'sa', 'kata', 'seion', NOW()),
  ('し', 'shi', 'hira', 'seion', NOW()),
  ('シ', 'shi', 'kata', 'seion', NOW()),
  ('す', 'su', 'hira', 'seion', NOW()),
  ('ス', 'su', 'kata', 'seion', NOW()),
  ('せ', 'se', 'hira', 'seion', NOW()),
  ('セ', 'se', 'kata', 'seion', NOW()),
  ('そ', 'so', 'hira', 'seion', NOW()),
  ('ソ', 'so', 'kata', 'seion', NOW()),
  ('た', 'ta', 'hira', 'seion', NOW()),
  ('タ', 'ta', 'kata', 'seion', NOW()),
  ('ち', 'chi', 'hira', 'seion', NOW()),
  ('チ', 'chi', 'kata', 'seion', NOW()),
  ('つ', 'tsu', 'hira', 'seion', NOW()),
  ('ツ', 'tsu', 'kata', 'seion', NOW()),
  ('て', 'te', 'hira', 'seion', NOW()),
  ('テ', 'te', 'kata', 'seion', NOW()),
  ('と', 'to', 'hira', 'seion', NOW()),
  ('ト', 'to', 'kata', 'seion', NOW()),
  ('な', 'na', 'hira', 'seion', NOW()),
  ('ナ', 'na', 'kata', 'seion', NOW()),
  ('に', 'ni', 'hira', 'seion', NOW()),
  ('ニ', 'ni', 'kata', 'seion', NOW()),
  ('ぬ', 'nu', 'hira', 'seion', NOW()),
  ('ヌ', 'nu', 'kata', 'seion', NOW()),
  ('ね', 'ne', 'hira', 'seion', NOW()),
  ('ネ', 'ne', 'kata', 'seion', NOW()),
  ('の', 'no', 'hira', 'seion', NOW()),
  ('ノ', 'no', 'kata', 'seion', NOW()),
  ('は', 'ha', 'hira', 'seion', NOW()),
  ('ハ', 'ha', 'kata', 'seion', NOW()),
  ('ひ', 'hi', 'hira', 'seion', NOW()),
  ('ヒ', 'hi', 'kata', 'seion', NOW()),
  ('ふ', 'fu', 'hira', 'seion', NOW()),
  ('フ', 'fu', 'kata', 'seion', NOW()),
  ('へ', 'he', 'hira', 'seion', NOW()),
  ('ヘ', 'he', 'kata', 'seion', NOW()),
  ('ほ', 'ho', 'hira', 'seion', NOW()),
  ('ホ', 'ho', 'kata', 'seion', NOW()),
  ('ま', 'ma', 'hira', 'seion', NOW()),
  ('マ', 'ma', 'kata', 'seion', NOW()),
  ('み', 'mi', 'hira', 'seion', NOW()),
  ('ミ', 'mi', 'kata', 'seion', NOW()),
  ('む', 'mu', 'hira', 'seion', NOW()),
  ('ム', 'mu', 'kata', 'seion', NOW()),
  ('め', 'me', 'hira', 'seion', NOW()),
  ('メ', 'me', 'kata', 'seion', NOW()),
  ('も', 'mo', 'hira', 'seion', NOW()),
  ('モ', 'mo', 'kata', 'seion', NOW()),
  ('や', 'ya', 'hira', 'seion', NOW()),
  ('ヤ', 'ya', 'kata', 'seion', NOW()),
  ('ゆ', 'yu', 'hira', 'seion', NOW()),
  ('ユ', 'yu', 'kata', 'seion', NOW()),
  ('よ', 'yo', 'hira', 'seion', NOW()),
  ('ヨ', 'yo', 'kata', 'seion', NOW()),
  ('ら', 'ra', 'hira', 'seion', NOW()),
  ('ラ', 'ra', 'kata', 'seion', NOW()),
  ('り', 'ri', 'hira', 'seion', NOW()),
  ('リ', 'ri', 'kata', 'seion', NOW()),
  ('る', 'ru', 'hira', 'seion', NOW()),
  ('ル', 'ru', 'kata', 'seion', NOW()),
  ('れ', 're', 'hira', 'seion', NOW()),
  ('レ', 're', 'kata', 'seion', NOW()),
  ('ろ', 'ro', 'hira', 'seion', NOW()),
  ('ロ', 'ro', 'kata', 'seion', NOW()),
  ('わ', 'wa', 'hira', 'seion', NOW()),
  ('ワ', 'wa', 'kata', 'seion', NOW()),
  ('を', 'wo', 'hira', 'seion', NOW()),
  ('ヲ', 'wo', 'kata', 'seion', NOW()),
  ('ん', 'n', 'hira', 'seion', NOW()),
  ('ン', 'n', 'kata', 'seion', NOW()),
  ('が', 'ga', 'hira', 'dakuten', NOW()),
  ('ガ', 'ga', 'kata', 'dakuten', NOW()),
  ('ぎ', 'gi', 'hira', 'dakuten', NOW()),
  ('ギ', 'gi', 'kata', 'dakuten', NOW()),
  ('ぐ', 'gu', 'hira', 'dakuten', NOW()),
  ('グ', 'gu', 'kata', 'dakuten', NOW()),
  ('げ', 'ge', 'hira', 'dakuten', NOW()),
  ('ゲ', 'ge', 'kata', 'dakuten', NOW()),
  ('ご', 'go', 'hira', 'dakuten', NOW()),
  ('ゴ', 'go', 'kata', 'dakuten', NOW()),
  ('ざ', 'za', 'hira', 'dakuten', NOW()),
  ('ザ', 'za', 'kata', 'dakuten', NOW()),
  ('じ', 'ji', 'hira', 'dakuten', NOW()),
  ('ジ', 'ji', 'kata', 'dakuten', NOW()),
  ('ず', 'zu', 'hira', 'dakuten', NOW()),
  ('ズ', 'zu', 'kata', 'dakuten', NOW()),
  ('ぜ', 'ze', 'hira', 'dakuten', NOW()),
  ('ゼ', 'ze', 'kata', 'dakuten', NOW()),
  ('ぞ', 'zo', 'hira', 'dakuten', NOW()),
  ('ゾ', 'zo', 'kata', 'dakuten', NOW()),
  ('だ', 'da', 'hira', 'dakuten', NOW()),
  ('ダ', 'da', 'kata', 'dakuten', NOW()),
  ('ぢ', 'ji', 'hira', 'dakuten', NOW()),
  ('ヂ', 'ji', 'kata', 'dakuten', NOW()),
  ('づ', 'zu', 'hira', 'dakuten', NOW()),
  ('ヅ', 'zu', 'kata', 'dakuten', NOW()),
  ('で', 'de', 'hira', 'dakuten', NOW()),
  ('デ', 'de', 'kata', 'dakuten', NOW()),
  ('ど', 'do', 'hira', 'dakuten', NOW()),
  ('ド', 'do', 'kata', 'dakuten', NOW()),
  ('ば', 'ba', 'hira', 'dakuten', NOW()),
  ('バ', 'ba', 'kata', 'dakuten', NOW()),
  ('び', 'bi', 'hira', 'dakuten', NOW()),
  ('ビ', 'bi', 'kata', 'dakuten', NOW()),
  ('ぶ', 'bu', 'hira', 'dakuten', NOW()),
  ('ブ', 'bu', 'kata', 'dakuten', NOW()),
  ('べ', 'be', 'hira', 'dakuten', NOW()),
  ('ベ', 'be', 'kata', 'dakuten', NOW()),
  ('ぼ', 'bo', 'hira', 'dakuten', NOW()),
  ('ボ', 'bo', 'kata', 'dakuten', NOW()),
  ('ぱ', 'pa', 'hira', 'dakuten', NOW()),
  ('パ', 'pa', 'kata', 'dakuten', NOW()),
  ('ぴ', 'pi', 'hira', 'dakuten', NOW()),
  ('ピ', 'pi', 'kata', 'dakuten', NOW()),
  ('ぷ', 'pu', 'hira', 'dakuten', NOW()),
  ('プ', 'pu', 'kata', 'dakuten', NOW()),
  ('ぺ', 'pe', 'hira', 'dakuten', NOW()),
  ('ペ', 'pe', 'kata', 'dakuten', NOW()),
  ('ぽ', 'po', 'hira', 'dakuten', NOW()),
  ('ポ', 'po', 'kata', 'dakuten', NOW()),
  ('きゃ', 'kya', 'hira', 'youon', NOW()),
  ('キャ', 'kya', 'kata', 'youon', NOW()),
  ('きゅ', 'kyu', 'hira', 'youon', NOW()),
  ('キュ', 'kyu', 'kata', 'youon', NOW()),
  ('きょ', 'kyo', 'hira', 'youon', NOW()),
  ('キョ', 'kyo', 'kata', 'youon', NOW()),
  ('しゃ', 'sha', 'hira', 'youon', NOW()),
  ('シャ', 'sha', 'kata', 'youon', NOW()),
  ('しゅ', 'shu', 'hira', 'youon', NOW()),
  ('シュ', 'shu', 'kata', 'youon', NOW()),
  ('しょ', 'sho', 'hira', 'youon', NOW()),
  ('ショ', 'sho', 'kata', 'youon', NOW()),
  ('ちゃ', 'cha', 'hira', 'youon', NOW()),
  ('チャ', 'cha', 'kata', 'youon', NOW()),
  ('ちゅ', 'chu', 'hira', 'youon', NOW()),
  ('チュ', 'chu', 'kata', 'youon', NOW()),
  ('ちょ', 'cho', 'hira', 'youon', NOW()),
  ('チョ', 'cho', 'kata', 'youon', NOW()),
  ('にゃ', 'nya', 'hira', 'youon', NOW()),
  ('ニャ', 'nya', 'kata', 'youon', NOW()),
  ('にゅ', 'nyu', 'hira', 'youon', NOW()),
  ('ニュ', 'nyu', 'kata', 'youon', NOW()),
  ('にょ', 'nyo', 'hira', 'youon', NOW()),
  ('ニョ', 'nyo', 'kata', 'youon', NOW()),
  ('ひゃ', 'hya', 'hira', 'youon', NOW()),
  ('ヒャ', 'hya', 'kata', 'youon', NOW()),
  ('ひゅ', 'hyu', 'hira', 'youon', NOW()),
  ('ヒュ', 'hyu', 'kata', 'youon', NOW()),
  ('ひょ', 'hyo', 'hira', 'youon', NOW()),
  ('ヒョ', 'hyo', 'kata', 'youon', NOW()),
  ('みゃ', 'mya', 'hira', 'youon', NOW()),
  ('ミャ', 'mya', 'kata', 'youon', NOW()),
  ('みゅ', 'myu', 'hira', 'youon', NOW()),
  ('ミュ', 'myu', 'kata', 'youon', NOW()),
  ('みょ', 'myo', 'hira', 'youon', NOW()),
  ('ミョ', 'myo', 'kata', 'youon', NOW()),
  ('りゃ', 'rya', 'hira', 'youon', NOW()),
  ('リャ', 'rya', 'kata', 'youon', NOW()),
  ('りゅ', 'ryu', 'hira', 'youon', NOW()),
  ('リュ', 'ryu', 'kata', 'youon', NOW()),
  ('りょ', 'ryo', 'hira', 'youon', NOW()),
  ('リョ', 'ryo', 'kata', 'youon', NOW()),
  ('ぎゃ', 'gya', 'hira', 'youon', NOW()),
  ('ギャ', 'gya', 'kata', 'youon', NOW()),
  ('ぎゅ', 'gyu', 'hira', 'youon', NOW()),
  ('ギュ', 'gyu', 'kata', 'youon', NOW()),
  ('ぎょ', 'gyo', 'hira', 'youon', NOW()),
  ('ギョ', 'gyo', 'kata', 'youon', NOW()),
  ('じゃ', 'ja', 'hira', 'youon', NOW()),
  ('ジャ', 'ja', 'kata', 'youon', NOW()),
  ('じゅ', 'ju', 'hira', 'youon', NOW()),
  ('ジュ', 'ju', 'kata', 'youon', NOW()),
  ('じょ', 'jo', 'hira', 'youon', NOW()),
  ('ジョ', 'jo', 'kata', 'youon', NOW()),
  ('びゃ', 'bya', 'hira', 'youon', NOW()),
  ('ビャ', 'bya', 'kata', 'youon', NOW()),
  ('びゅ', 'byu', 'hira', 'youon', NOW()),
  ('ビュ', 'byu', 'kata', 'youon', NOW()),
  ('びょ', 'byo', 'hira', 'youon', NOW()),
  ('ビョ', 'byo', 'kata', 'youon', NOW()),
  ('ぴゃ', 'pya', 'hira', 'youon', NOW()),
  ('ピャ', 'pya', 'kata', 'youon', NOW()),
  ('ぴゅ', 'pyu', 'hira', 'youon', NOW()),
  ('ピュ', 'pyu', 'kata', 'youon', NOW()),
  ('ぴょ', 'pyo', 'hira', 'youon', NOW()),
  ('ピョ', 'pyo', 'kata', 'youon', NOW())
ON CONFLICT (character, script) DO NOTHING;
